spring.datasource.username = root
spring.datasource.password = Katerina99
spring.datasource.url = jdbc:mysql://localhost:3306/photo_app
spring.jpa.hibernate.ddl-auto=update
tokenSecret = 12312sdasdasd